## **General**
1- What's the difference between a Machine Learning (ML) Model and a Machine Learning algorithm.

2- Why we need to study Linear Algebra for ML?

# Responses:
1-The machine learning model is what we obtain after training, it's a sort of a function that takes input "new data" and try to predict. 
Machine learning algorithm is an algorithm that we apply on our dataset to obtain the model. (like : Naive Bayes, Knn, Id3 ..)

2-We need to study linear algebra for example to know how to manupilate matrices, which are very important in ML.
 -matrices are used to represent data  

**## Vectors:**

**1- create a vector: **

Our vector can be written as v=(2,1), but more formally we would use the following notation, in which the dimensional coordinate values for the vector are shown as a matrix:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$

In [ ]:
import numpy as np
#TO DO...
v = np.array([[2],
              [1]])


print(v)

[[2]
 [1]]


### **2-Calculating Magnitude**

In [ ]:
import math
#TO DO... 
magnitude = math.sqrt((v[0]**2)+(v[1]**2))
print(magnitude)


2.23606797749979



**3- Vector Addition:**
So far, we've worked with one vector at a time. What happens when you need to add two vectors.

Let's take a look at an example, we already have a vector named v, as defined here:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$Now let's create a second vector, and called s like this:$$\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}$$

And we have :$$\vec{z} = \vec{v}+\vec{s}$$

In [ ]:

import math
import numpy as np

v = np.array([[2],
              [1]]) 
s = np.array([[-3],
              [2]])
z = v + s
print (z)

[[-1]
 [ 3]]



4- Dot Product Multiplication


$$ \vec{d}=\vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})$$

In [ ]:

import math
import numpy as np

v = np.array([[2],
              [1]]) 
s = np.array([[-3],
              [2]])
d = v.transpose().dot(s)
print (d)

[[-4]]


## **Matrices:**

# 1- create a Matrice:
A matrix arranges numbers into rows and columns, like this:

$$A = \begin{bmatrix}
  1 &amp; 2 &amp; 3 \\
  4 &amp; 5 &amp; 6
 \end{bmatrix}
$$

In [ ]:
import numpy as np

A = np.arange(1, 7).reshape(2, 3)
print (A)

[[1 2 3]
 [4 5 6]]



#2- Matrix Transposition
You can transpose a matrix, that is switch the orientation of its rows and columns. You indicate this with a superscript T, like this:

$$\begin{bmatrix}1 &amp; 2 &amp; 3 \\4 &amp; 5 &amp; 6\end{bmatrix}^{T} = \begin{bmatrix}1 &amp; 42 &amp; 53 &amp; 6 \end{bmatrix}$$

a- How can we do it mathematically? 
Each column become a row



b- with Python: 

In [ ]:
import numpy as np

A = np.arange(1, 7).reshape(2, 3)
A = A.transpose()
print(A)



[[1 4]
 [2 5]
 [3 6]]


## **Eigendecomposition:**

So we've learned a little about eigenvalues and eigenvectors; but you may be wondering what use they are. Well, one use for them is to help decompose transformation matrices.

1- How can we decompose a matrix? ( Rules and steps)
2- (Bonus) Do it in python with your exampls.

Eigendecompostion is used to diagonalize a matrix , first we have to calculate its eigenvalues and eigenvectors 

In [ ]:
#2 bonus
import numpy as np